### ISSUE TITLE
reflection fails with custom serializer for std::chrono types on clang/gcc

### ISSUE THREAD

**Issue by jeff-kohn** [stephenberry/glaze#1066]
Howdy,

I'm using glaze to parse some data that contains date/times as well as durations (which are just an integer count of seconds). I want to use some chrono types for these values, so I wrote some custom serializers based on your examples. Originally writing the code in MSVC 19.x, everything worked as expected, but when I went to test on linux I get compilation errors. Minimal example:

Godbolt link: https://gcc.godbolt.org/z/G4zhKKG7v

```
#include <string>
#include <chrono>
#include <iostream>
#include <glaze/glaze.hpp>

static constexpr std::string_view json =  R"(
   {
      "message": "Hello",
      "seconds_duration": 5458
   }
)";

namespace chrono = std::chrono;

namespace glz::detail
{
   template <>
   struct from_json<chrono::seconds>
   {
      template <auto Opts>
      static void op(chrono::seconds& value, is_context auto&& ctx, auto&&... args)
      {
         int32_t sec_count{};
         read<json>::op<Opts>(sec_count, ctx, args...);
         if (glz::error_code::none == ctx.error)
            value = chrono::seconds{ sec_count };
      }
   };
} // namespace glz::detail


struct chrono_data
{
   std::string  message{};
   chrono::seconds seconds_duration;
};


int main(int, char** )
{
   auto data_result = glz::read_json<chrono_data>(json);
   if (data_result)
      std::cout << "Message '" << data_result->message << "' had duration of " << data_result->seconds_duration << std::endl;
   else
      std::cerr << "Error - " << glz::format_error(data_result.error(), json) << std::endl;
   return 0;
}

```

On clang/gcc, this code doesn't compile with an error stating "error: type 'chrono_data' decomposes into 2 elements, but only 1 name was provided". If I put the seconds_duration member first, the code compiles but at runtime I get a parse error "unknown key". It seems like the compile-time reflection code stops when it hits the chrono::seconds member, so the meta data for my struct is incomplete.

Am I doing something wrong, or is this a compiler-specific compile-time reflection bug?

**Comment by dbraeckelmann** [comment]
I noticed the same regression (https://github.com/stephenberry/glaze/issues/907#issuecomment-2155815741).

Reverting 438d3e8408851c5216c6c81e59346065dc97087a fixes it for me:
`git revert 438d3e8408851c5216c6c81e59346065dc97087a -X theirs --no-edit`

**Comment by stephenberry** [comment]
Thanks for reporting this. I'm looking into a solution.

**Comment by jeff-kohn** [comment]
One thing I should point out that may be relevent, I'm not on the latest release of glaze since I'm using it thru vcpkg. So this issue goes back a little while at least on gcc/clang. Behavior is the same as seen with using trunk on godbolt though.

**Comment by stephenberry** [comment]
I posted this in #907, but here is some context for the issue:

So, the problem is that reverting https://github.com/stephenberry/glaze/commit/438d3e8408851c5216c6c81e59346065dc97087a breaks #907 with std::optional broken with reflection as the first member. The addition of const fixed the std::optional problem as well as some others. Removing the initializer list construction from count_members fixes both cases, but breaks counting C style arrays.

Currently MSVC is not compliant with the C++ standard, and I have an open issue here: https://developercommunity.visualstudio.com/t/Bad-aggregate-initializable-handling-us/10664400

However, they are reticent to fix the bug as the wording around conversion operators may change soon. However, from reading the paper the wording should change in favor of supporting what Glaze wants.
https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2828r1.html

From the paper:

If the selected constructor is a copy or move constructor ([class.copy.ctor]) for T, the braced-init-list contains a single element, and the implicit conversion sequence ([over.best.ics.general]) for the constructor's first parameter would bind that parameter to the result object of a conversion function whose return type is T (ignoring cv-qualification), that conversion function is called to initialize the object.
This is what Glaze has, a single element in an initializer list whose return type is T, so MSVC and GCC ought to construct T and not fail as they currently do.

I'll continue to work with MSVC and GCC, but it's hard to find solutions when they aren't standard compliant.

There is actually another solution to counting members with requires and structured bindings, but MSVC, GCC, and Clang all have compiler errors here that I plan to report, and I don't expect this solution to be viable in the near term.

**Comment by stephenberry** [comment]
`std::chrono` types cause additional issues, and Clang breaks because `std::chromo::duration` has two template arguments. It appears to me that this is a compiler bug with Clang, because the conversion operator to T (`std::chrono::seconds`) should win out.

**Comment by stephenberry** [comment]
After a lot of experimenting I'm thinking the best solution is to break reflection for C style arrays. Using C style arrays in Glaze will require a `glz::meta` definition. I think this makes more sense because Glaze is a C++ library and users can in most cases change their C style arrays to use `std::array`. This also simplifies the member counting code so the compilers will act more similarly across MSVC, GCC, and Clang.

If users need C style array support, they can still do so manually through a `glz::meta` definition.

**Comment by stephenberry** [comment]
Support is being worked on in #1097. I've added the custom std::chrono code here as a test case.
