### ISSUE TITLE
Update to v3.2.2 causes compilation errors

### ISSUE THREAD

**Issue by romanholidaypancakes** [stephenberry/glaze#1254]
You can use the code here to reproduce:
https://github.com/stephenberry/glaze/issues/827

Maybe you can add the sample code inside as part of the test case

**Comment by stephenberry** [comment]
It looks like this error is because you are not compiling with C++23 (`-std=c++23`). Can you confirm? Glaze `v3.0.0` bumps the requirement to `c++23` so that performance improvements can be made and development streamlined.

**Comment by stephenberry** [comment]
You can stay on `v2.9.5` for C++20 support. But, I'm curious what prevents you from using C++23? [All compilers that supported Glaze in C++20 also support C++23.]

Looking at where we want Glaze to be in a few years it made sense to transition now, so that the core architecture doesn't have to hack around limitations in C++20 (static constexpr in functions is a big one). A lot of times macros can be used around new features, but when it comes to `static constexpr` in functions it changes the way interfaces are built, how many functions are generated, and how compile time algorithms are written. So, in the long run we would have thousands of lines of different code between C++20 and C++23, which would make feature development slower and harder to test. We also plan to slowly adopt more features from C++23 as they become available on all the compilers, as they will have significant performance improvements (`std::flat_map`, `resize_and_overwrite`, etc.). These new features can just have version macros in many cases, so we can maintain backwards compatibility, but it prevents us from needing to maintain three different implementations as we improve the codebase.

**Comment by stephenberry** [comment]
Thanks for the info. Glaze `v3` and above is supported with vs2022 using `/std:c++latest` and tested in our CI/CD. The CMake `cxx_std_23` flag will set this as well.

I'm curious what makes upgrading to C++23 not easy? Is it deprecated features and old, unsafe code that you need to build? Or, are you wanting to prevent developers from using C++23 features and affecting dependencies?

If the desire for C++20 in `v2` is high enough I will consider back porting bug fixes, but the performance and feature improvements will be in `v3`.

**Comment by stephenberry** [comment]
I appreciate your feedback and there are some risks. But, there is no upgrade to a new compiler needed here, it is just changing the standard version, which is backwards compatible except for a few deprecations that will reveal issues that should be fixed. When changing the standard version it doesn't mean it runs a completely separate version of the compiler, it mostly means that new features are now allowed, but the old features would compile the same as they did before. The same code is used in the compiler to build the old codebase. I also work with teams that can be slow to increment language versions, but it is usually due to using older compilers.

I realize I can't influence your department heads, so I'm sorry for the trouble this causes. But, we're trying to plan for the future where we will have an even bigger disparity in versions between C++23 and C++26 when reflection arrives. The intention is to maintain Glaze support for both C++23 and C++26 and `v3` of Glaze makes this much easier to manage. The aim was to design `v3` so that we can implement various reflection mechanisms side by side, so that the transition to C++26 will be smoother. That may seem like a long ways away, but it is core to the design of Glaze and I've learned that five years goes by quick and one often wishes they had planned for the future.

**Comment by stephenberry** [comment]
Sounds good, thanks for providing feedback on this project! I'll close this issue, but definitely open more issues if you encounter any more problems.
