### ISSUE TITLE
About exceptions handling

### ISSUE THREAD

**Issue by Bolderaysky** [stephenberry/glaze#153]
I found that glaze is throwing exceptions by default. First looking at the code and repo, I find that glaze doesn't support exception-free mode. Is it possible to implement that for using glaze in projects with no exceptions?

```
glaze/include/glaze/util/parse.hpp:262:48: error: exception handling disabled, use ‘-fexceptions’ to enable
  262 |          throw std::runtime_error("not a digit");
  ```

**Comment by stephenberry** [comment]
Yeah, we currently don't have a no exception option for JSON. Binary reading/writing doesn't throw errors, as it expects proper data generated from the library.

We plan to implement a no exception compile time option for JSON, but there is actually a performance loss when going to another error handling approach (exceptions allow us to reduce the number of branch checks). We also want to make sure we're not over complicating the code base and have a good implementation. But, I have an idea I'll experiment with.

Do you have a target platform that doesn't allow exceptions?

Thanks for bringing this up and hopefully it will be tackled soon.

**Comment by Bolderaysky** [comment]
Thanks for your answer!

Mainly, these platforms are Linux and macOS, where I disable exceptions and do everything explicitly.

It is possible to work around that by compiling a part of the project that uses Glaze as a shared library and only use exceptions in that library. However, it would be great to see such an opportunity in Glaze, since there are platforms where the use of exceptions is not allowed at all.

**Comment by Peanhua** [comment]
Just to add more encouragement :) I also have need for non-exception style interface, but in a bit different situation:

I'm trying to use Glaze in what you call "generic JSON" style. In the JSON data that I have it is perfectly normal for some JSON nodes sometimes be there and sometimes not. Using exceptions for handling the "not" -cases seems counter-intuitive, because for me exceptions are for abnormal situations, but these use cases are perfectly normal.

Currently, if I understand correctly, there is no other way than catching an exception when trying to access, for example:
```
glz::json_t json;
glz::read<glz::opts{.no_except=true}>(json, some_string_input);
std::cout << json["sdf"].get<std::string>() << "\n";
```
The above will throw an exception ```std::bad_variant_access```.
The previous json library I used had the possibility to do a check with something like:
```
if(json["sdf"].is_string())
  ...
```
Something similar would be nice, I don't need Glaze to be "fully exception free", just having these type of query function(s) would be perfect for my case.


Also, couple nice to have features for arrays:
If getting array would return empty array if the node does not exist, then I could just write the following without needing to make any checks and worry about exceptions if the "sdf" node does not exist:
```
for(auto x : json["sdf"].get<std::vector<glz::json_t>>())
  ...
```
And a shortcut for that particular get() call without needing to specify `std::vector<glz::json_t>`, something like the following would be easier for my old eyes:
```
for(auto x : json["sdf"].give_me_an_array())
  ...
```

**Comment by stephenberry** [comment]
@Bolderaysky The no_except branch (#156) has been merged, so you can now build with -fno-exceptions
