### ISSUE TITLE
Unable to create json_t object with int value

### ISSUE THREAD

**Issue by Peanhua** [stephenberry/glaze#163]
I'm not able to construct `json_t` object when trying to initialize it with an `int` value:
```
$ cat g.cc
#include <iostream>
#include <glaze/glaze.hpp>

int main()
{
  glz::json_t json = { {"i", 1} };
  //  std::cout << json["i"].get<int>() << "\n";
}
$ g++ -std=c++20 g.cc
g.cc: In function ‘int main()’:
g.cc:6:33: error: could not convert ‘{{"i", 1}}’ from ‘<brace-enclosed initializer list>’ to ‘glz::json_t’
    6 |   glz::json_t json = { {"i", 1} };
      |                                 ^
      |                                 |
      |                                 <brace-enclosed initializer list>
$ g++ --version
g++ (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ 
```

**Comment by mwalcott3** [comment]
#164 allows for initialization using non-double numeric types like int.

double is the only numeric type stored in json_t since it allows us to use the built-in automatic auto variant type inferencing when there is only one of each fundamental type. This is done on purpose to simplify the implementation.

So ```glz::json_t json = { {"i", 1} };``` will work now but you would need to use json["i"].get<double>()

**Comment by Peanhua** [comment]
Thanks :) I'm converting a piece of software to use Glaze, where I use json data (passing the json_t around) for loading&saving, and for internal undo/redo buffer in the GUI. I'm not using more than an `int` when stuffing integer data into json, so the limitations of the range are of no concern for me now.

Having a convenience method `json["i"].as<int>()` like you suggest would be nice indeed.

For removing the limits on integer range, maybe you could consider to translate integer values internally to a string (instead of double) when you parse them in, and then have the convenience methods like `get.as<uint64_t>()` convert them to the integer type asked. Converting such integer values to/from string is what I would probably do as a user of the library if I needed the increased range of integer values with json_t.

I'm not sure why reference scripting languages with a C++ library, so I'll skip that :)

**Comment by mwalcott3** [comment]
Convenience methods to perform numeric and string conversions were added in 32459c006f73a3b5cc12cca24a497bc489113135. The below text is mainly for my own reference when we revisit wider integer support in glz::json_t and can be ignored/skipped.

Storing nums as strings when out of range like @Peanhua pointed out is a pretty good idea. Lazy conversions can also be beneficial since string to number conversions are pretty costly. This also gets rid of any runtime costs associated with type deduction. Sometime in the future, we may add that as well as the efficient auto deduction of integer and floating point types for generic json and variants. 

But for now, I think this is fine. I prefer delaying stuff until someone has a good use case. If someone has an immediate need we are much more open to prioritizing those than things that we anticipate might be nice to have ([YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it)). 

Note that while wider integer support is nice it's not required by the JSON standard so it is typically not a good thing to depend upon anyways if using multiple different implementations.
> Note that when such software is used, numbers that are integers and
   are in the range [-(2^53)+1, (2^53)-1] are interoperable in the
   sense that implementations will agree exactly on their numeric
   values.
https://www.rfc-editor.org/rfc/rfc7159#section-6

We do support 64-bit ints in the typed mode since we don't have to pay any runtime cost for the type deduction. Typically there has been much more emphasis on typed reading/writing since C++ is a typed language. glz::json_t was a bit of an afterthought after we had basic variant support since it was essentially free. glz::json_t is just a thin wrapper around a std::variant since recursive std::variants are not a thing and with the addition of glaze_value_t doesn't require library features and could have been implemented by a user and would be automatically handled.  I think adding something like a named discriminator for tagged unions https://www.rfc-editor.org/rfc/rfc8927#name-discriminator might help reduce the use cases for generic json.

As a side note from looking back at the code I should update json_t to use glaze_value_t rather than the current nullable unwrapping strategy as it does impose a slight unnecessary runtime cost since variant deduction is already capable of handling the null case. Also, I think std::map was used since heterogenous lookup is slightly easier but std::unordered_map should generally be preferred for performance on larger objects.
