### ISSUE TITLE
Store type hash as std::array<uint64_t, 2> for optimal comparison performance

### ISSUE THREAD

**Issue by stephenberry** [stephenberry/glaze#168]

**Comment by mwalcott3** [comment]
I was somewhat curious about the perf difference https://quick-bench.com/q/pAJeQPdR_YlEFZ3XJPqC35By67A

Provided one string_view is constexpr it is about even which makes sense since it knows the size compiletime and can generate essentially the same code for the memory comparison (Minus an extra size check) but if neither std::string_view values are constexpr it is about 5-8x slower depending on the compiler because it ends up calling memcmp.

I don't think any of our comparisons use 2 runtime hashes but it's still better safe than sorry.

**Comment by mwalcott3** [comment]
Handled in #202
