### ISSUE TITLE
Add option to allow parsing NaN as double

### ISSUE THREAD

**Issue by Allybag** [stephenberry/glaze#170]
I realise it is disallowed by the JSON spec, but I have a data source I do not control who send down NaNs in double fields sometimes.

Would it be possible to add a glz::opt that would parse "NaN" as `std::numeric_limits<double>::quiet_NaN`?

**Comment by mwalcott3** [comment]
Addressed in #171. It will read NaN by default since NaN is quite common despite not being standard JSON. Python json.dumps() will write it out for instance. A force_conformance option is being added in #156 for people to prevent reading in non conforming JSON if they want.

My opinion on the matter:
- Writing out invalid JSON is not acceptable unless requested for explicitly.
- Reading in invalid JSON by default is fine for common stuff like "NaN" or unescaped tab characters in strings. This is provided supporting these things doesn't add overhead when parsing conformant JSON.
- People should have the option to force conformance when reading.

**Comment by Allybag** [comment]
Excellent, thanks for sorting this out so quickly!
