### ISSUE TITLE
mingw is failing and I don't know why

### ISSUE THREAD

**Issue by stephenberry** [stephenberry/glaze#287]
I'll look more into this later, but @mwalcott3 let me know if you see a way to fix this.

**Comment by mwalcott3** [comment]
Ill have to look into this more later as well.

The only things that happened since the last successful run was automatic clang formatting changes and a version bump.

msys2 and mingw are being pulled in dynamically so it is more likely related to updated packages.

The last successful build was pulling in
mingw-w64-x86_64-gcc-12.2.0-11
And the failing build is pulling in
mingw-w64-x86_64-gcc-13.1.0-3-any

Im slightly concerned that this will impact gcc 13 in general as all of our current tests are on gcc 10,11,or 12.

**Comment by stephenberry** [comment]
Fixed in #313
