### ISSUE TITLE
Feature Request: Accept extra fields

### ISSUE THREAD

**Issue by sweihub** [stephenberry/glaze#307]
Hi Mr @stephenberry 

Thanks for your team for the amazing project. Howerver, will you accept extra fields?

For example, I have a trade program which connects to Binance with websocket/rest-api, all works well, but someday, Binance add an extra fields to a response JSON, which will fail my program. But this is OK for Java/JavaScript world. The redundant field should not be considered as an error.

The testing code
```cpp
struct Location {
    int x;
    int y;
    int z;
};

GLZ_META(Location, x, y, z);

void glaze_test()
{
    // missing z in string, OK
    auto point = glz::read_json<Location>(R"( {"x":10, "y":20} )");
    if (point) {
        printf("missing z is OK!\n");
    }

    // extra t in string, error
    auto space = glz::read_json<Location>(R"( {"x":10, "y":20, "z":30, "t":12345} )");
    if (!space) {
        printf("extra t is error: %d\n", space.error().ec);
    }
}
```

Output
```
missing z is OK!
extra t is error: 21
```

**Comment by stephenberry** [comment]
Glaze has a bunch of compile time options, one of which is to turn off erroring on unknown keys.

Instead of calling glz::read_json(...), you can call `glz::read<glz::opts{}>(...)` and customize the options.

`glz::read<glz::opts{.error_on_unknown_keys = false}>(...)` will turn off erroring on unknown keys and instead skip the items. This is what you want.

You can also change the format here, but `.format = glz::json` is the default.

**Comment by sweihub** [comment]
Holy, I just know this option, thanks, that solved my issue!
