### ISSUE TITLE
Is there any way to support a non-standard container?

### ISSUE THREAD

**Issue by toge** [stephenberry/glaze#361]
I am using a std::unordered_{set,map} compatible container called [unordered_dense](https://github.com/martinus/unordered_dense).

I think it would be more efficient if I could directly convert data between this container and glaze.
Is there any way to support a non-standard container?

**Comment by justend29** [comment]
Glaze uses templates and concepts to allow the conversion functions it provides applicability to any container that offers the necessary operations. The specializations of `from_json` and `to_json` provided with glaze - the internal conversion functions to/from json/containers - are not fully specialized to standard containers at all, they are partially specialized with concepts.

Additionally, should the provided, internal `from_json` and `to_json` conversion functions provided with glaze be insufficient for any of your purposes, you can [provide specializations](https://github.com/stephenberry/glaze/blob/main/docs/custom-serialization.md) for them in your code-base to suit your needs.

To your use-case with the *unordered_dense* library, here's an example of glaze (de)serializing both dense maps and sets from that library without any custom conversion code. These work because the dense map & set meet the concept requirements of glaze's provided conversions for maps & sets.

```c++
#include <string>

#include <ankerl/unordered_dense.h>
#include <glaze/json/read.hpp>
#include <glaze/json/write.hpp>

int main() {
  // round-trip example with dense map
  using Dense_map = ankerl::unordered_dense::map<int, std::string>;
  const Dense_map map{{123, "hello"}, {987, "world"}};

  const auto serialized_map = glz::write_json(map);
  assert(serialized_map == R"({"123":"hello","987":"world"})");

  const auto parsed_map = glz::read_json<Dense_map>(serialized_map);
  assert(parsed_map.has_value());
  assert(parsed_map.value() == map);

  // round-trip example with dense set
  using Dense_set = ankerl::unordered_dense::set<int>;
  const Dense_set set{1, 2, 3, 4, 5, 5, 5, 5};

  const auto serialized_set = glz::write_json(set);
  assert(serialized_set == R"([1,2,3,4,5])");

  const auto parsed_set = glz::read_json<Dense_set>(serialized_set);
  assert(parsed_set.has_value());
  assert(parsed_set.value() == set);
}
```

**Comment by toge** [comment]
@justend29 
Thanks a lot!
glaze always works great for me!
