### ISSUE TITLE
Error parsing nullable quoted_num

### ISSUE THREAD

**Issue by stephanyuan** [stephenberry/glaze#541]
When I define a quoted_num field as optional, reading json is not working as expected. Same scenario works fine for common optional fields(non-quoted_num e.g. std::string).

What I am expecting is this quoted_num field can be empty string, or it can be not presented in the json at all, without triggering parsing error or missing key error since it is defined as optional(nullable).

See below sample code:

```cpp
// works fine as expected
static constexpr std::string_view json = R"(
{"num":"123","str":"abc" }
)"; 

// expect no error but get below error:
// error: 2:9: parse_number_failure
//    {"num":"","str":"abc" }
//           ^
static constexpr std::string_view json = R"(
{"num":"","str":"abc" }
)"; 

// expect no error but get below error:
// error: 2:15: missing_key
//    {"str":"abc" }
//                 ^
static constexpr std::string_view json = R"(
{"str":"abc" }
)"; 

struct msg_t {
    std::optional<double> num;
    std::string           str;
};

template <> struct glz::meta<msg_t> {
    using T                     = msg_t;
    static constexpr auto value = object("num", quoted_num<&T::num>, "str", &T::str);
};

int main(int argc, char* argv[]) {
    msg_t obj;
    auto  error = glz::read<glz::opts{.error_on_unknown_keys = false, .error_on_missing_keys = true}>(obj, json);
    if (error) {
        auto descriptive_error = glz::format_error(error, json);
        std::cout << "error: " << descriptive_error << std::endl;
    } else {
        if (obj.num.has_value()) {
            std::cout << "str: " << obj.str << ", num: " << obj.num.value() << std::endl;
        } else {
            std::cout << "str: " << obj.str << std::endl;
        }
    }
}
```

**Comment by justend29** [comment]
I agree - empty strings should by default produce an error when using `quoted_num` because you are explicitly stating *"parse numbers that are enclosed in strings"*, which an empty string is not.

Nevertheless, handling an explicit `null` value seems the appropriate way to convey *no quoted string value*, which is currently not supported with `quoted_num`. Would adding that support be appropriate?

**Comment by stephanyuan** [comment]
@stephenberry I agree on this point that empty `quoted_num` is more of an error. What actually bothers me is the inconsistency reading behavior between `std::string` filed type and `quoted_num` field type when they are defined as optional(nullable).

For example, say I have `error_on_missing_keys` set to `true`:

**Comment by stephanyuan** [comment]
Yeah, I actually am required to handle empty quotes rather than `null`, read the doc and thought optional would be my choice. But anyway, I agree on this point that empty `quoted_num` is more of an error. 

Another point would be the inconsistent missing-key-error-handling between `string` type and `quoted_num` type when they are defined as nullable.

For example, say I have `error_on_missing_keys` set to `true`:
```cpp
// missing string type key, glz::read returns success
{"num":"123"}  
struct msg1_t {
    std::string                num;
    std::optional<std::string> str;
};

// missing quoted_num type key, glz::read returns missing_key error
{"str":"abc"} 
struct msg2_t {
    std::optional<double> num;
    std::string           str;
};
```

**Comment by stephenberry** [comment]
In #932 I merged in support for the major features requested in this issue.
- Wrappers like `quoted_num` now behave like nullable types when they contain a nullable type
- `error_on_missing_keys` now doesn't error if the optional is not set, like other nullable types

I did not add support for parsing empty strings as null optionals. I feel like this is a corner case that probably should be handled through a custom parser using `glz::custom` or `glz::to_json/glz::from_json`.

I'm going to close this issue because of the major improvements, and if you need assistance creating a custom parser, feel free to post another issue or discussion.
