### ISSUE TITLE
Unable to read variant when default initialized to different variant index

### ISSUE THREAD

**Issue by eliotheinrich** [stephenberry/glaze#635]
The following code:

```
#include <iostream>
#include <variant>
#include <glaze/glaze.hpp>

using var = std::variant<std::string, int, double>;

struct my_struct {
  var val{1};
};

int main() {
  my_struct st1{"hello world"};

  std::string buffer = glz::write_json(st1);
  buffer = glz::prettify(buffer);
  std::cout << buffer << std::endl;

  my_struct st2;
  auto pe = glz::read_json(st2, buffer);
  std::string descriptive_error = glz::format_error(pe, buffer);
  std::cout << descriptive_error << std::endl;
}
```
gives an error on ```read_json```; it prints
```
{
   "val": "hello world"
}
2:11: parse_number_failure
      "val": "hello world"
             ^
```
It seems that it fails whenever `val` is default-initialized to a different type than `st1` is initialized to later. 

Also, when the variant no longer includes double (i.e. `using var = std::variant<std::string, int>`), then `val` can be safely reassigned from an int to a string and vice versa without issue.

**Comment by stephenberry** [comment]
Yes, this is a known limitation to automatic variant deduction, because the JSON specification treats all numeric values as the same. So, by including both `int` and `double` you are making your variant not auto-deducible. See [documentation](https://github.com/stephenberry/glaze/blob/main/docs/variant-handling.md)

We could add support for partial automatic deduction for your string type in this case, but it makes things more confusing for users if only some types will be deduced.

You could only include `double` in your variant and then cast this to an int when you want an int. Or, you can use tags for your variants (see [documentation](https://github.com/stephenberry/glaze/blob/main/docs/variant-handling.md).

If automatic deduction is not possible for your type combination then the variant will attempt a load into the active state, which in your example is an integer, which is why you get a `parse_number_failure` error.

I hope this makes sense. And, please add your thoughts if you think there's a good solution to this.
