### ISSUE TITLE
Behaviour of glz::detail::count_members

### ISSUE THREAD

**Issue by Zischen** [stephenberry/glaze#721]
Consider the following:

```
struct V2
{
    float x;
    float y;

    V2() = default;

    V2(V2&&) = default;
    V2(const float* arr) : x(arr[0]), y(arr[1]) {}
};

template <>
struct glz::meta<V2>
{
    static constexpr auto value = object(&V2::x, &V2::y);
};

struct V2Wrapper
{
    V2 x;
};

int main()
{
    int n = glz::detail::count_members<V2Wrapper>;
    printf("%i\n", n);
}
```

In this example, `n==0`, and so serializing `V2Wrapper` produces the empty string. If I comment out either the move constructor or the `float*` constructor in `V2` then `count_members` returns 1 and everything is fine.

Would it be possible to error out when this occurs (like for V2 itself the library errors and suggests implementing glz::meta but this mechanism doesn't extend to the wrapper)? Perhaps there could also be a way to manually give it the count rather than having to specify each field in glz::meta in this case?

**Comment by stephenberry** [comment]
I'm looking into this. Interestingly, `count_members` returns `n==1` on clang and behaves how you'd like. I'm not sure which compiler is actually behaving correctly yet.

**Comment by stephenberry** [comment]
I found a solution to your problem. In order to make your `V2` struct countable (on GCC/MSVC) and therefore reflectable with the V2Wrapper, you need to add an initializer list constructor. I have make a simple alias in Glaze to avoid conflicting with other constructors.

All you need to do is add the following constructor to your V2 struct: `V2(glz::make_reflectable) {}`

In full:
```c++
struct V2
{
   float x{};
   float y{};

   V2(glz::make_reflectable) {}
   V2() = default;

   V2(V2&&) = default;
   V2(const float* arr) : x(arr[0]), y(arr[1]) {}
};
```
