### ISSUE TITLE
write_json does not skip null optional when using quoted_num or custom

### ISSUE THREAD

**Issue by Oipo** [stephenberry/glaze#725]
I'm currently working on writing an Etcd v3 REST client, but it seems there's a bug in Etcd where setting a field to null gives different results than omitting the field entirely.

Regardless of real-world use cases, it would be nice to have the `skip_null_members` function on `quoted_num` and `custom` fields as well.

Code:
```c++
#include <glaze/glaze.hpp>
#include <iostream>

struct one final {
    std::optional<int64_t> opt;
};
struct two final {
    std::optional<int64_t> opt;
};
struct three final {
    std::optional<int64_t> opt;
};

template <>
struct glz::meta<one> {
    using T = one;
    static constexpr auto value = object(
            "opt", quoted_num<&T::opt>
    );
};

template <>
struct glz::meta<two> {
    using T = two;
    static constexpr auto value = object(
            "opt", &T::opt
    );
};

template <>
struct glz::meta<three> {
    static constexpr auto read_opt = [](three &req, std::optional<std::string> const &s) {
        if(s) {
            req.opt = std::stoll(*s);
        }
    };
    static constexpr auto write_opt = [](three const &req) -> std::optional<std::string> {
        if(!req.opt) {
            return std::nullopt;
        }
        return std::to_string(*req.opt);
    };

    using T = three;
    static constexpr auto value = object(
            "opt", custom<read_opt, write_opt>
    );
};

int main() {
    {
        one o{};
        std::string buf;
        glz::write_json(o, buf);
        std::cout.write(buf.c_str(), static_cast<int64_t>(buf.size())) << "\n";
    }
    {
        two o{};
        std::string buf;
        glz::write_json(o, buf);
        std::cout.write(buf.c_str(), static_cast<int64_t>(buf.size())) << "\n";
    }
    {
        three o{};
        std::string buf;
        glz::write_json(o, buf);
        std::cout.write(buf.c_str(), static_cast<int64_t>(buf.size())) << "\n";
    }

    return 0;
}
```

Output:
```
oipo$ g++ -std=c++20 -O2 -I ../external/glaze/include/ GlazeOptional.cpp && ./a.out 
{"opt":null}
{}
{"opt":null}
oipo$ clang++ -std=c++20 -O2 -I ../external/glaze/include/ GlazeOptional.cpp && ./a.out 
{"opt":null}
{}
{"opt":null}
oipo$ g++ --version
g++ (GCC) 13.1.1 20230611 [master r13-6340-g4341106354c]
oipo$ clang++ --version
Ubuntu clang version 19.0.0 (++20240203115900+6ad692b7b341-1~exp1~20240204000020.1476)
```

**Comment by stephenberry** [comment]
This would be a good feature to add. Will look into it after fixing some more pressing bugs in Glaze.

**Comment by stephenberry** [comment]
From recent updates, wrappers like `glz::quoted_num` now behave like nullable values when they contain `std::optional`. So, some of your request is now supported.

I attempted adding support for `glz::custom`, but it is simply too complicated, because the compiler needs to look through so much compile time logic to determine the return type. The Clang compiler was segfaulting on me.

If you want optional-like handling with custom structures then you can use the `to_json/from_json` specialization approach, where your wrapper struct declares `static constexpr bool glaze_wrapper = true;` and `using value_type = T;`. This is how `glz::quoted_num` and other wrappers work, and would allow you to avoid printing a null value.

Nullable handling will probably be improved in the future, but I'm going to close this issue as at least a portion of it was accomplished and the `glz::custom` request is just infeasible right now.

Sincerely,
Stephen
