### ISSUE TITLE
Document need for asio to be included by the user and add compile time errors

### ISSUE THREAD

**Issue by yurivict** [stephenberry/glaze#744]
The build succeeds w/out asio.hpp

**Comment by stephenberry** [comment]
Yes, that is intentional. It would be a burden on users to force all users of Glaze to include asio. With Glaze being a support library it means you are free to include the features you'd like.

It is up to the user to include asio if they are using asio features. We could make a separate CMake file for including asio, but Glaze isn't interested in being a CMake support library for third party libraries.

The same is true for Eigen, which Glaze has supported for a long time, and which users must include themselves if they want those features.

I do need to document this further and I think we can add static_asserts to explain this requirement if the header files are not found, which would be helpful for users. So, I'll keep this issue open for those things.
