### ISSUE TITLE
Arrays partial read support

### ISSUE THREAD

**Issue by g-virus-dev** [stephenberry/glaze#761]
It would be nice to have a partial read support for arrays as it's done for objects, if it's possible due to Glaze's design.

For example, in data size sensitive systems you can find the following continuous JSON stream:

```json
... begin of stream
[0, 1, 2, "data1", "data2", false],
[1, 1, 4, "data1", "data2", false, 430.56, [true, false], "data3"],
[2, 1, 6, true]
.. end of stream
```

where the first element of an array indicates a type of the array and thus a way to understand the rest of the data, and sometimes you just need to parse arrays with type 2 only (just 4 elements). But in the current implementation you can't just declare a tuple like this

```cpp
std::tuple<int,int,int> data;
```
 cause it breaks down parsing with syntax_error.

**Comment by stephenberry** [comment]
This should be easier to implement than partial object reading and is a great idea.

**Comment by jeff-kohn** [comment]
I'd love to see this as well.  I'm working with some JSON data that contains objects with several dozen properties, of which I only want to use a subset. I initially thought I could do this with the partial read support as described [here](https://github.com/stephenberry/glaze/pull/719), but after testing realized it won't work for me even with partial_read_nested, because the json I'm getting back actually contains arrays of these objects.  

It looks like if I want to make this work currently I would have to list all the properties in the meta data, skipping the ones I don't need (or just adding them to my structs even though I don't need them).

**Comment by stephenberry** [comment]
Note that you can read from a specific element using JSON pointer syntax in Glaze. [See documentation](https://github.com/stephenberry/glaze/blob/main/docs/json-pointer-syntax.md)

**Comment by stephenberry** [comment]
I'm considering adding a `read_allocated` compile time option and wrapper, which would allow you to write:
```c++
std::tuple<int,int,int> data;
glz::read<glz::opts{.read_allocated = true}>(data, buffer);
```

This would read only into the allocated memory of the tuple and then early exit. This concept can be applied to runtime arrays and even objects.

**Comment by stephenberry** [comment]
Support for partial reading via the `read_allocated` option has been added. The option supports quick exiting for types like std::tuple, std::array, std::vector, std::map, std::unordered_map, glaze meta objects, and reflected structs.

**Comment by stephenberry** [comment]
The new read_allocated option was confusing in its name. It has been renamed to partial_read.
read_allocated would imply that you only read allocated memory, but this is confusing for strings, which we read in completely. We only want partial reading of objects are array types.

Merge request #1028 will contain the `partial_read` name for the compile time option. The merge also has useful documentation concerning partial reading.
