### ISSUE TITLE
allowing tag property in tagged variant objects

### ISSUE THREAD

**Issue by TimonNoethlichs** [stephenberry/glaze#928]
Hi, first off: I really enjoy your library and the performance is awesome! Huge thanks from me and my team!

I have the following code:

```
struct OptionA {
  std::string tag;
  int a;
};

struct OptionB {
  std::string tag;
  int a;
};

using TaggedObject = std::variant<OptionA, OptionB>;

template <>
struct glz::meta<std::variant<OptionA, OptionB>> {
  static constexpr std::string_view tag = "tag";
  static constexpr auto ids = std::array{"A", "B"};
};
```

and it gives me the following error when trying to parse it:

```
parsing failed: 1:22: no_matching_variant_type
   { "tag": "A", "a": 2 }
                        ^
```

When I remove the tag property from the structs it works. Is there a way to fix this issue and keep the additional tag property in the structs?

Here is the example in Compiler Explorer: https://godbolt.org/z/5EfGsWThf

Best Regards,
Timon

**Comment by stephenberry** [comment]
Glad you're enjoying the library. I've just made a merge request (#929) that will close this issue soon. The former code could not use automatic deduction because the members were all the same, and because it had a member matching the tag name, it never tried to use the tag approach. This has been fixed with changing the order of operations, so now we attempt to decode from the tag first.
