### ISSUE TITLE
[MSVC] `write_json` fails with `std::unordered_map<std::uint32_t, std::string>`

### ISSUE THREAD

**Issue by helmesjo** [stephenberry/glaze#938]
Hi! Great library, I just hit a little snag (skimmed through docs/tests but couldn't see this mentioned).

**Example** (`v2.5.3`, VS `v17.9.6`)
```c++
std::unordered_map<std::uint32_t, std::string> uint32_string;
(void)glz::write_json(uint32_string); // fails to compile
std::unordered_map<std::string, std::uint32_t> string_uint32;
(void)glz::write_json(string_uint32); // works
```

**Error**
```
glaze/json/write.hpp(515): error C2027: use of undefined type 'glz::quoted_t<_Ty1>'
        with
        [
            _Ty1=const unsigned int
        ]
C:\git\b2\build2-glaze\libglaze\include\glaze/json/read.hpp(32): note: see declaration of 'glz::quoted_t<_Ty1>'
        with
        [
            _Ty1=const unsigned int
        ]
```

**Comment by stephenberry** [comment]
This should totally work. It looks like MSVC introduced an error with their latest release. I added your test case here #939, which passes, and there were already similar tests that have been passing.

I can upgrade my version of MSVC to this latest version and test myself. Will get back to you soon.

**Comment by stephenberry** [comment]
So, I was able to successfully build and run the code using MSVC `v17.9.6` (the latest). What header files are you including to use Glaze? It might be a header include issue. Or, it might be some other setup problem on your side.

**Comment by helmesjo** [comment]
Interesting... These are my includes (in this order):
```c++
#include <glaze/binary/read.hpp>
#include <glaze/binary/write.hpp>
#include <glaze/core/common.hpp>
#include <glaze/json/read.hpp>
#include <glaze/json/write.hpp>
```

**Comment by stephenberry** [comment]
Yeah, integer keys need `quoted.hpp` because the keys must be quoted. And quoted acts as a special wrapper, so it exists in its own header.

This will likely be improved/refactored in the future, but for now using numeric keys needs `quoted.hpp` to be included. I usually recommend using `glaze/json.hpp` for general JSON usage, but it does include more headers than you need. I'm going to close this issue as I don't intend to make a specific change to address this complexity, but expect that it will be improved in the long term. C++20 modules support when added should also remove the need for partial includes.
