### ISSUE TITLE
Support `format_error()` (& specifically `details::get_source_info()`) for binary `parse_error`?

### ISSUE THREAD

**Issue by helmesjo** [stephenberry/glaze#949]
There currently is no support (AFAICS) for stringifying a `parse_error` when returned from `read_binary()`. 
Should there be an overload for `details::get_source_info()` that deals with `BEVE`? Or change so it can be either some "string-like type" (assume `JSON`), or some "binary-like" type (assume `BEVE`)? I don't know the details of that function, so maybe it should be used differently (or not at all) when dealing with binary parsing errors?

**Comment by stephenberry** [comment]
I was thinking about this the other day and I do think more information should be given about the error context for binary parsing. However, binary parsing errors should be extremely rare and not relied upon. I just added a warning comment about binary error checking to [the documentation here](https://github.com/stephenberry/glaze/blob/main/docs/binary.md).

Binary should not be written by hand and checksum mechanisms should be employed when sending across a network (or use protocols like TCP). The only way you would have parsing errors is if higher level validation and security mechanisms were broken or the code itself had errors (which is checked via unit testing). I have been adding more read parsing errors, but I'm undecided whether I should test all corner cases, because it causes a drop in performance for tests that shouldn't be needed if proper higher level safety mechanisms are used.

**Comment by helmesjo** [comment]
I see. In my case I'm just wrapping up `glaze` to do serialization/deserialization, and if something fails (however it can fail) I return my own `parse_error` consisting of `error_code` and `msg`. So I guess however much or little context can be given by `glaze`, it'd be nice if the same `format_error()` method can be reused (makes it easier to handle in generic code).
IMO it's totally fine if it just says `"binary read error"` and `"binary write error"` for the time being.

**Comment by stephenberry** [comment]
I'm merged in support for your primary request. You can now handle `parse_error` using buffers of `std::byte`. The buffer context isn't given, but the index of the error is provided. The biggest benefit is that you can use `glz::format_error` for both binary and json.

**Comment by helmesjo** [comment]
You're a trooper, thanks!
