### ISSUE TITLE
Stack overflow when returning intermediate object to serialize in_addr

### ISSUE THREAD

**Issue by kalmjasper** [stephenberry/glaze#995]
Hey there!

First of all thanks a lot for writing this library! It makes serialising / deserialising data so much easier...

When I was trying to serialise an `af_inet` object without intermediate allocations (`std::string`) I got a stack overflow at runtime, this seems like a pretty reasonable approach to me to accomplish this (https://godbolt.org/z/jK6K3M1cq for full example):

```
template <size_t N>
struct FixedName {
    FixedName() : len(0) {}
    std::array<char, N> buf;
    uint16_t len;

    struct glaze {
        static constexpr auto value = [](FixedName& self) -> auto { return std::string_view(self.buf.data(), self.len); };
    };
};

template <>
struct glz::meta<in_addr> {
	static constexpr auto value = [](in_addr &self) -> FixedName<INET_ADDRSTRLEN> {
		FixedName<INET_ADDRSTRLEN> val;

		inet_ntop(AF_INET, &self, val.buf.data(), INET_ADDRSTRLEN);
		val.len = std::char_traits<char>::length(val.buf.data());
		return val;
	};
};
```

What's going wrong here? It doesn't seem to me like there should be a difference between this and returning an std::string in terms of the lifetime of the stack of the returned object. The string should be fully copied instead of having the heap allocated object being passed around, saving the allocation should definitely be worth it performance wise.

Am I overseeing something here or is this a bug in glaze?

**Comment by stephenberry** [comment]
What you are doing looks correct. From debugging quickly it looks like this is an issue with nested lambda calls in Glaze. The `glz::meta` value is invoking a lambda that invokes the `FixedName` lambda. This should work, but it appears to be misinterpreting the nested lambda as a nullable. So, yes this is a bug in Glaze. But, it shouldn't be too difficult to fix.

**Comment by stephenberry** [comment]
Ah, I discovered this is not a Glaze bug, but rather a bug in your code. Your `glz::meta<in_addr>` returns an Rvalue of `FixedName<INET_ADDRSTRLEN>`. However, your `glaze` definition in `FixedName` only accepts Lvalues. If you change `[](FixedName& self)` to `[](cosnt FixedName& self)` or `[](FixedName&& self)`, to either accept a const lvalue or an rvalue then your code will run as desired.

This does bring up the question of whether we can catch these errors at compile time. But, I don't currently see a straightforward solution, because the lambda approach needs to be extremely flexible and support rvalues, lvalues, etc. It can also return nullable types and function pointers, so it's very hard to determine what is appropriate. Eventually we may be able to improve the code to catch these errors, but for now make sure that your functions support rvalues.

**Comment by stephenberry** [comment]
I added a test case based on your example to the code with a comment about the challenges of detecting this user error. #996

**Comment by stephenberry** [comment]
Glad you're finding the library useful. Let me know if you run into any more issues.

**Comment by kalmjasper** [comment]
Thanks it's working perfectly now! Makes sense that you can't cast an rvalue in an lvalue.

For my understanding: How does this not result in a compile time bug but rather in a runtime bug? Passing an rvalue to a function that only accepts an lvalue seems like a compile time thing to catch

**Comment by stephenberry** [comment]
From my debugging it looks like the lambda is convertible to an lvalue function pointer, so it continually tries to deference and then create a new pointer to the lambda. I think this bug could probably be caught, but it's confusing to debug.
